services:
  - type: web
    name: employee-tracker
    env: python
    region: singapore
    buildCommand: "./build.sh"
    startCommand: "cd backend && gunicorn tracker_backend.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: employee-tracker-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: tracker_backend.settings

databases:
  - name: employee-tracker-db
    databaseName: employee_tracker
    user: employee_tracker_user
    region: singapore
